service: bgclambda
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource:
        - "arn:aws:s3:::bgcdesafioigorcatalogo/*"
  apiGateway: {
      shouldStartNameWithService: true,
    }

functions:
  catalogo:
    handler: catalogo.handler
    events:
      - http: 
          path: catalogo
          method: get  
          cors: true
    environment:
      bucket: "bgcdesafioigorcatalogo"
  mailsender:
    handler: mailsender.handler
    events:
      - http: 
          path: mailsender
          method: post
          cors: true  
    environment:
      bucket: "bgcdesafioigorcatalogo"
      user: "igor.bgc.exodo@gmail.com"
      password: "bgcmeaceita123"

